.travis.yml, README.md, jest-puppeteer.config.js, jest.config.js, src/js/custom_element.js, src/js/events.js, src/js/index.js, src/js/scroll_panel.js, src/js/table.js, src/js/tbody.js, src/js/thead.js, src/js/utils.js, test/js/two_billion_rows.test.js
Adds [Travis CI](https://travis-ci.org/github/jpmorganchase/regular-table) continuous builds.
=> Adds Travis CI

.travis.yml, babel.config.js, package.json, src/config/umd.config.js, src/js/events.js, src/js/scroll_panel.js, src/js/tbody.js, src/js/utils.js
This PR remove lodash and core-js builtins, wihch simplifies the build and cuts ~15k of javascript from the UMD build.  Also fixes annoyingly dense travis warnings due to deprecated `yarn`.
=> Smaller `regular-table.js` Asset

examples/file_browser.html, src/js/custom_element.js, src/less/material.less, test/file_browser.test.js
Updates #19 from @telamonian to rely on the new `row_headers` feature introduced in #24 .  The `add-filebrowser-example` branch was first rebased:
* Commit history was squashed to 1 commit
* Changes to `tree_row_header.js` and 'events.js` were removed.
* Changes to `perspective.html` were removed (which relied on the above).
* README.md changes reverted (no need to add your example to the gallery - I'll do this automatically via script when I dist).
Next, the example was refactored.  Unfortunately some of my comments from the original PR were quickly outdated by rapid progress on this API.
* Removes `__config`, `__collapse` and `__expand` pass-through.
* Uses `row_headers` instead of `row_indices`, et al columns.
* Adds a custom tree_header renderer ala `perspective.html`, modified to …
=> Adds file_browser.html example (update for `row_headers` feature)

README.md, examples/2d_array.html, examples/canvas_data_model.html, examples/file_browser.html, examples/minesweeper.html, examples/perspective.html, examples/perspective_headers.html, examples/two_billion_rows.html, examples/virtual_indices.html, examples/web_worker.html, package.json, scripts/sync_gist.js, src/js/custom_element.js, src/js/scroll_panel.js, src/js/thead.js, src/js/utils.js
This PR fixes many small style and CSS bugs, as well as clarifies some API methods:
* `setDataModel()` is now `setDataListener()`
* `addEventListener('regular-table-after-updates')` is now `addStyleListener()`, which will help prepare for `async` support on these callbacks.
=> Updated examples and documentation

examples/benchmark.html, src/js/constants.js, src/js/custom_element.js, src/js/index.js, src/js/utils.js
* Refactors log-based performance monitoring to `getDrawFPS()` method, which returns stats collected since last invocation.
* Adds `benchmark.html`, which scrolls as fast as `setInterval()` allows and logs FPS to a toaster popup,  to glorify feature.
=> Add benchmark.html and `getDrawFPS()`

examples/canvas_data_model.html, examples/perspective_headers.html, examples/spreadsheet.html, src/js/scroll_panel.js, src/js/table.js, src/js/tbody.js, src/js/thead.js, test/spreadsheet.test.js, test/two_billion_rows/metadata.test.js
A `<td>` within a `<table>` has a number of interesting metadata values which this PR now calculates more-correctly:
* `size_key` - a unique column ID (including row header `<th>` columns.
* `cidx` - the index within the current `<tr>`.
* `x` and `y` - the corresponding indices into the `data` property returned by the data model.
Also adds a motivating example which requires precise data spatial awareness, `spreadsheet.html`, which uses `contenteditable` to implement a simple Excel-style app complete with an expression language with range syntax support:
=> `spreadsheet.html` Example

examples/canvas_data_model.html, examples/file_browser.html, examples/minesweeper.html, examples/perspective_headers.html, examples/spreadsheet.html, examples/two_billion_rows.html, scripts/sync_gist.js
Adds transform to `sync_gist` script which extracts the license header, as well as the following HTML comment block which it uses to generate a `README.md`.  Such `README` descriptions have been added to the example gallery.
Also generates a `.block` header for repos which lack one explicitly.
Fixes #30
=> Adds LICENSE and README info to example gists

examples/fixed_column_width.html, test/fixed_column_width.test.js
This pull request adds support for fixed column widths by applying custom attributes `maxWidth` and `minWidth` to the cells of the `<regular-table/>` ensuring that the columns don’t grow or shrink past the attributes’ limits. Adds a new example:
* This contribution includes `fixed_column_width.html`, an example use of the fixed column width feature allowing developers to explore and extend its implementation.
=>  Add support for fixed column widths

examples/spreadsheet.html, test/examples/spreadsheet.test.js
Fixes a regression in `spreadsheet.html`, which relied on deprecated `Metadata` properties.  Also adds a test for the affected functionality.
=> Fixes example regression and adds a test

src/js/scroll_panel.js, src/js/table.js, src/js/tbody.js, test/examples/two_billion_rows.test.js
Fixes a bug in column resize behavior which caused `override` column widths to apply to the wrong columns when scrolling horizontally.
=> Fix sticky column resize behavior

src/js/constants.js, src/js/events.js, src/js/scroll_panel.js, src/less/container.less, src/less/material.less, test/examples/spreadsheet.test.js, test/examples/two_billion_rows.test.js, test/examples/web_worker.test.js, test/features/getMeta.test.js, test/features/scrolling.test.js
Rebased and amended version of #36.
* The main fix alters regular-table virtual position calculations to use `clientWidth` and `clientHeight` over `offsetWidth`, `offsetHeight`, where appropriate, to handle non-zero-width scrollbars.
* Removes style code which was hard to `material` theme.
* Hardcodes non-overlay scrollbars to the material theme, since it is more important this theme be
consistent.
=> Firefox fix

src/js/index.js, src/js/table.js, src/js/tbody.js, test/features/getMeta.test.js
This PR exposes the `x1` and `y1` passed to the `DataListener` when invoked via `MetaData`.
=> Add x1, y1 to getMeta()

examples/canvas_data_model.html, examples/file_browser.md, index.d.ts, package.json, src/js/index.js, test/examples/2d_array.test.js, test/examples/two_billion_rows.test.js, test/features/scrollTo.test.js, yarn.lock
I've tested this PR out by `yarn linking`-ing it into an external typescript project. The typings seems to work well.
- 4069dec - this one adds the actual `index.d.ts`
- 9bd534d - minor fixups to jsdocs to match 4069dec
- 1406f41  - fixes #54: renamed `scrollTo` -> `scrollToCell`, so that the method can be included in `index.d.ts` without the typescript compiler complaining about shadowing of the base class method
@texodus 9bd534d added docstrings for the `RegularTableElement` private methods:
- on the genreral principle that the more (dev) docs, the better
- I added `@internal @private` tags to the private docstrings. In theory, that means these private docstrings will get ignored both by jsdoc and [at least one declaration generator](https://api-extractor.com/pages/setup/configure_rollup …
=> Adds manually written index.d.ts typescript type declaration

examples/striped.md
It was a bit difficult to appreciate the styling changes on scroll with such a large data set.
This PR introduces a helper function `generateDataListener ()` that could be reused for other tests and limits the data set to 10k rows making the example easier to use.
=> Make data model smaller size for ease of use in `striped.md` example

examples/perspective.md, src/js/constants.js, src/js/events.js, src/less/material.less, test/examples/area_mouse_selection.test.js, test/examples/spreadsheet.test.js
Fixes bugs:
* Fixes `perspective.md` to generate a well-formed response when the underlying `Table` is empty.  `perspective` itself returns an empty object in this case, though arguably it should provide the column_header keys, this is still potentially logically empty in the case of `column_pivots`.
* Fixes a CSS quirk which makes interaction events apply `::select` pseudoclass and styling.
* Fixes a regression in iOS which causes virtual scrolling to "bounce" along with the headers in a fairly unattractive way, at the expense of scroll inertia.  We may need to revisit this if scroll inertia is a popular feature ...
=> Bug fixes for `perspective.md` and iOS

examples/perspective.md, src/js/index.js, src/js/table.js
Adds a public `clear()` method, which explicitly resets the rendering state to an empty `<table>`.
=> Adds `clear()` method

examples/perspective.md, package.json, src/js/events.js, src/js/index.js, src/less/material.less, test/examples/spreadsheet.test.js, yarn.lock
* Fixes the `replace()` method.  The previous implementation reset `innerHTML`, but a subtle race condition allowed the old DOM nodes to still be updated by `regular-table`;  the new `clear()` replaces the entire `table_model`.
* Fixes a few unintentional mouse interactions:
* Clicking on the tree axis itself.
* Clicking on the "corner" and applying a sort of a negative column ..
=> Fix `replace()` and unintentional interactive elements.

examples/perspective.md, test/examples/perspective.test.js
For the `perspective.md` example, a new `perspective.View()` can be created for each new sort config;  but when used as a basis for a `<perspective-viewer>` component, which manages and generates its own `perspective.View()`, we must delegate this responsibility externally, which this PR adds via a simple `CustomEvent`, `"regular-table-psp-sort"`, wihch is registered in the `.markdown` example's `html' top-level section.
=> Refactor perspective.md sort to abstract mutable state via sorting

src/js/constants.js, src/js/index.js, src/js/scroll_panel.js, src/js/tbody.js
Adds the `swap` option for the `draw()` method, which replaces the existing constant value.  With this change, `<table>` swapping will _only_ occur when this flag is set.
```javascript
table.draw({swap: true});
```
In addition, the container element used for 'staging" changes during a swap has been moved to the light DOM, as a child of `<regular-table>`, sibling to the visible `<table>` container element.  This allows CSS style which may impact layout, such as font size and cell dimensions, to be calculated correctly in swapped mode; as a side effect however,  naive of async calls to `querySelector()` may resolve both hidden and cloned visible table elements.
=> `swap` option for `draw()`

src/js/scroll_panel.js
Styles `swap` container element using `"opacity:0:z-index:-1:pointer-events:none"`, which (unlike `"display:none"`) allows correct dimension to be calculated during a `draw({swap: true})`.  This is applied inline due to its structural importance - this element should never be visible, even in the absence of an accompanying stylesheet.
=> Style `swap` container element to visible

src/js/events.js
When `regular-table` is embedded in a page or `HTMLElement` which is scrollable, the `<regular-table>` custom element will `preventDefault()` mousewheel and touch events, causing these actions to not scroll the parent.  As do embedded scrollable standard `HTMLElements`s already, this PR makes `<regular-table>` stop intercepting these events when the scroll container is at its min or max position.
=> Don't preventDefault() scroll when the table is at scroll min or max

examples/perspective.md
Fixes a rendering issue with `perspective.md` example's `dataListener()` method, which caused it to generate malformed `regular-table`responses in the presence of column pivots who become empty due to the presence of filter conditions.
=> Fixed `perspective` example bug

src/js/index.js
The browser complains loudly and there may be some other side effects (e.g. in `perspective`'s fat webpack bundle when used with other libraries that leverage regular-table, such as `ipyregulartable`)
=> Don't attempt to register web component if already created

examples/canvas_data_model.md, examples/perspective.md, jest.config.js, package.json, src/js/events.js, src/js/index.js, src/js/scroll_panel.js, src/js/table.js, src/js/thead.js, src/js/utils.js, test/examples/fixed_column_widths.test.js, test/examples/perspective.test.js, test/examples/spreadsheet.test.js, test/features/scrollTo.test.js, test/features/scrolling.test.js, yarn.lock
A few big-picture API cleanup changes in this PR, and a few bugs:
* Refactors `perspective.md` model to separate `dataListener()` and `formatStyleListener()` into separate functions.  
* `styleHandler`s are now invoked incrementally when a column's widths are not known, with total width calculation being deferred until pagination.  This clears up a whole category of resize bugs involving columns failing to render for _just_ the first call to `draw()`.
* The default DOM structure has been simplified (due to browser bug fixes since publication) to remove an intermediate `<div>` layer.
```javascript 
<regular-table>
<div>
<table></table>
</div>
</regular-table>
```
vs.
```javascript 
<regular-table>
<table></table>
</regular-table>
```
* Fixes overscroll behavior due to browser "bounce" on …
=> Incrementally call styleHandlers, and remove intermediate <div>

index.d.ts, src/js/events.js, src/js/index.js, src/js/scroll_panel.js
Fixes #110
This PR fixes the typos and other minor issues in the jsdocs mentioned in #110, carries those fixes over to the typescript typings in `index.d.ts`, and makes a couple of other minor by-hand fixes to `index.d.ts`, such as including the `.draw` method in the `RegularTableElement` typing
=> Fixup jsdoc annotations, carry fixups over to typescript typings

README.md, examples/fixed_column_widths.md, examples/perspective.md, src/js/index.js, src/js/scroll_panel.js, src/js/table.js, src/js/thead.js, src/js/view_model.js, test/examples/fixed_column_widths.test.js, test/examples/spreadsheet.test.js, test/features/scrollTo.test.js, test/features/scrolling.test.js
From the new documentation for this feature:
> To prevent DOM renders, `<regular-table>` conserves DOM calls like `offsetWidth` to an internal cache.  When a `<td>` or `<th>`'s `width` is modified within a callback to `.addStyleListener()`, you must indicate to `<regular-table>` that its dimensions have changed in order to invalidate this cache, or you may not end up with enough rendered columns to fill the screen!
>
> A call to `invalidate()` that does not need new columns only imparts a small runtime overhead to re-calculate virtual width per async draw iteration, but should be used conservatively if possible.  Calling `invalidate()` outside of a callback to `.addStyleListener()` will throw an `Error`.
```javascript
table.addStyleListener(() => {
for (const th of …
```
=> Invalidate

src/js/constants.js, src/js/scroll_panel.js, src/js/table.js, src/js/thead.js, src/js/utils.js
Before calling `StyleListener` callbacks, remove nodes which are not part of this render pass.  This replicates behavior from before the introduction of the incremental rendering feature, and prevents `StyleListener` callbacks from styling nodes which lack metadata.
=> Clean and autosize columns in incremental render passes

examples/row_mouse_selection.md, scripts/sync_gist.js, test/examples/row_mouse_selection/selecting_one_row_range.test.js, test/examples/row_mouse_selection/splitting_one_row_range.test.js
Make Row Selection available on row click / selection.
Move Row Selection to a blocks compatible example.
=> Update features / example - allow row selection anywhere

examples/area_clipboard.md, examples/area_mouse_selection.md, examples/row_mouse_selection.md, examples/row_stripes.md, scripts/sync_gist.js, test/examples/row_mouse_selection/selecting_one_row_range.test.js, test/examples/row_mouse_selection/splitting_one_row_range.test.js, test/examples/row_stripes.test.js
This PR exports `addAreaMouseSelection()` allowing it to be consumed as a lib function.
It also converts the Area Mouse Selection example to a block compatible version.
=> Make area selection block example

examples/area_clipboard.md, examples/area_mouse_selection.md, examples/column_mouse_selection.md, examples/row_mouse_selection.md, examples/row_stripes.md, scripts/sync_gist.js, test/examples/column_mouse_selection/selecting_column_headers.test.js, test/examples/column_mouse_selection/selecting_one_column_range.test.js, test/examples/column_mouse_selection/splitting_one_column_range.test.js, test/examples/row_mouse_selection/selecting_one_row_range.test.js, test/examples/row_mouse_selection/splitting_one_row_range.test.js, test/examples/row_stripes.test.js
Export the `addColumnMouseSelection()` function and make column selection available as a blocks example.
=> Make column selection blocks example

examples/perspective.md, src/js/thead.js, test/examples/column_mouse_selection/selecting_column_headers.test.js, test/examples/column_mouse_selection/selecting_one_column.test.js, test/examples/column_mouse_selection/selecting_one_column_range.test.js, test/examples/column_mouse_selection/selecting_two_columns.test.js, test/examples/column_mouse_selection/splitting_one_column_range.test.js, test/examples/perspective.test.js, test/examples/row_column_area_selection/column_selection.test.js
As discussed with @texodus, this PR changes the creation of column header nodes such that any text is wrapped up in a `<span>` element before getting added. As opposed to now, where any text is just included as a raw text node.
=> wrap any plain text column headers in a `<span>`

examples/row_stripes.md, index.d.ts, src/js/index.js, src/js/scroll_panel.js, test/examples/row_stripes.test.js
This is a breaking change because it changes the return value of `addStyleListener`. That being said, the return value wasn't particularly useful because there was no public API to remove subscribed listeners.
=> Return an unsubscribe function from `addStyleListener`

README.md, examples/perspective.md, package.json, src/js/events.js, src/js/index.js, src/js/scroll_panel.js, src/less/container.less, yarn.lock
Adds an optional argument `virtual_mode` to the `setDataListener()` method.
```javascript
table.setDataListener(listener, {virtual_mode: "vertical"})
```
There are four virtual modes supported, including the previous (now default) behavior `"both"`.  The three new values each disable one or both virtual scroll axes:
* "both" (default) virtualizes scrolling on both axes.
* "vertical" only virtualizes vertical (y) scrolling.
* "horizontal" only virtualizes horizontal (x) scrolling.
* "none" disable all scroll virtualization.
Note that using a `virtual_mode` other than the default `"both"` will render the _entire_ `<table>` along the non-virtual axis(es), and may cause rendering performance degradation.
=> Add 'virtual_mode' optional argument to `setDataListener()`

index.d.ts
See https://reactjs.org/docs/web-components.html#using-web-components-in-react
Although this change can be viewed as breaking, I wouldn't personally call it such - if you pass `className`, then the class doesn't get applied. This is a bug fix in my opinion, and it allows consumers to correctly pass `class` prop.
=> Replace unsupported `className` prop with `class` in TypeScript typings

features/literally.config.js, scripts/sync_gist.js, src/js/events.js, src/js/table.js, src/js/tbody.js, src/js/view_model.js
Fixes buggy column-resize behavior when the actual header edge which was clicked on belongs to a column group.  Before:
After:
=> Fix column group resize

features/area_clipboard.md, features/row_column_area_selection.md
I was working through https://github.com/jpmorganchase/regular-table/blob/master/features/row_column_area_selection.md#adding-the-behaviors for https://github.com/jpmorganchase/ipyregulartable/issues/47 and noticed what seemed to be a few paths reference js files in `examples` that seem to be listed in `features` instead
=> update paths from examples to features

README.md, src/js/events.js, src/js/scroll_panel.js, src/js/table.js, src/js/tbody.js
* Adds a new key `metadata` to the Data Listener Response API, which uses an identically dimensioned `Array` to pass non-rendered metadata to Style Listeners.  This key may be used to e.g. supply color, font or opacity information to a Style Listener from the data model, without rendering this information into the DOM first.
* Shfit+dblclick on a column header now resets _all_ column widths to their auto-size defaults.
* A few rendering fixes as well, which minimize the number of page relayout events are triggered from (1) sudden resize events (e.g. panel collapse), and (2) column resizing.
=> Metadata API

src/js/table.js, src/js/thead.js
Previously, while subsequent calls to `draw()` would re-use pre-existing DOM elements such as `<th>` when appropriate, they would pro-actively clear `className` before applying the default classes and calling style handlers.  This PR removes this behavior, which suppresses some re-renders at the expense of requiring `styleListener()` implementations to both `set` _and_ _`reset`_ any classes they wish to modify (where currently they only need implement `set`, since `draw()` would clear the `className` itself).  `regular-table`'s examples all already had this behavior, but this is nonetheless a breaking change.
The old behavior may be trivially implement in a `styleListener` by resetting `className`:
```javascript
table.addStyleListener(() => {
for (const td of table.querySelectorAll("td, …
```
=> Preserve classname

.gitignore, CONTRIBUTING.md, declarationsconfig.json, index.d.ts, package.json, src/js/index.js, src/js/scroll_panel.js, yarn.lock
This PR makes significant fixes to the typings, as well as adding a mostly automated build for (re)generating the contents of the `index.d.ts` typescript declaration file:
- Typing fixes:
- Automated build:
=> Update typings for 0.4.0; add 99% automated typescript declarations build

src/js/index.js, src/js/table.js, src/js/thead.js, src/js/view_model.js
* Memoize `<span>` elements (used in column headers).
* During auto size, calculate width via `parseFloat(window.getComputedStyle(elem).width)`, which returns the sub-pixel units necessary to remove a small flicker when column auto-sizing is performed.
=> Memoize `<span>` elements

jest.config.js, src/less/container.less, test/examples/spreadsheet.test.js
When re-sizing (shrinking) a container containing a `<regular-table>`, the `.rt-table-clip` container with `position: sticky` will sometimes emit a blank frame, causing the table to flicker, only in Chrome.  I've tried a whole laundry list of fixes, including but not limited to:
* Alternatives to `sticky`
* `fixed` without `position` works but stutters on Safari and overlaps scroll bars on the parent web component.
* `absolute` with Javascript `position` update stutters on keyboard scroll.
* `-webkit-transform: translate3d(0, 0, 0)`, `transform: translateX(0)`, `backface-visibilitiy: hidden` and various layout-acceleration-forcing CSS properties.
`contains: strict` on the sticky element itself seems to finally do the trick.  This really shouldn't have any affect on `regular-table`, since …
=> Fix screen thrash when "position: sticky" container resize is triggered

src/js/scroll_panel.js
`virtual_mode` only sets `position: sticky` on a single axis for some values, so we need to disable `contain: strict` else the overflow will not render.
=> Fix `virtual_mode` CSS bug

babel.config.js, examples/spreadsheet.md, features/fixed_column_widths.md, index.d.ts, src/js/events.js, src/js/index.js, src/js/scroll_panel.js, src/js/table.js, src/js/thead.js, test/examples/spreadsheet.test.js, test/features/scrollTo.test.js
Previously, horizontal scrolling was calculated by evenly distributing the available `scrollWidth` among the viewable columns.  This worked fine and arguably made cell-aligned-scrolling more pleasant, but caused a perceived scroll position drift when the `regular-table` dimensions were changed as the `scrollWidth` / `offsetWidth` ratio changed.  This PR makes this behave linear with the column sizes, so e.g. scrolling through a 200px column will take twice as many pixels as a 100px column.  This scrolling model works better (arguably) with sub-cell scrolling introduced in `0.5.0`, and more importantly does not cause position drift.
=> Linear column scrolling

src/js/scroll_panel.js
Fixes a miscalculation in width which caused some jitter when width is slightly larger than viewport.
=> Fix a miscalculation in row_header offsets

src/js/scroll_panel.js
Fix errors when `.draw()` called on a hidden, detached or 0-sized `<regular-table>`.
=> Fix errors when `.draw()` called on empty viewport/invisible element

src/js/utils.js
Calls to `<regular-table>`'s async `.draw()` method are _debounced_ while the previous `.draw()` call is still being processed.  Calls debounced in this manner are then squashed when the previous call completes, with only the last such call being invoked, the assumption being that all previous calls have been superseded.  The async mutex which implements the debounce behavior was mistakenly set to the class object however, causing `.draw()` calls to multiple `<regular-table>`s on the same page to debounce each other;  this PR moves the async mutex to the instance instead.
=> Fix debounce interference between multiple `regular-table`

AUTHORS, README.md
~~- JP Morgan Chase should be on the LICENSE and NOTICE files~~
- FINOS "active" and OpenSSF "passing" badges
- Contributing + License sections added to readme
=> Update to License, Notice and Readme files

src/js/events.js, src/js/scroll_panel.js, src/js/table.js
* Fixes a bug which causes the viewport to be calculated as too small (due to memoizing a bad row height).
* Fixes a bug which causes a deadlock (unresponsive grid) when shrinking a column below its autosize minimum.
=> FIx column resize & row height viewport bugs

README.md, src/js/scroll_panel.js, src/js/table.js, src/js/thead.js
Adds two new non-data-specific configuration options to the schema of the `dataListener` return object:
* `column_header_merge_depth: number` configures the number of rows to include
from `colspan` merging. This defaults to `header_length - 1`.
* `row_height: number` configures the pixel height of a row for
virtual scrolling calculation. This is typically auto-detected from the DOM,
but can be overridden if needed.
=> Add `column_header_merge_depth` and `row_height` page options

src/js/thead.js, src/less/material.less
Changes the behavior of `column_header_merge_depth` to also calculate auto-sizing relative to the specified override depth.
=> Fix autosize to use last merged column header

src/js/view_model.js, test/features/row_mouse_selection/selecting_grouped_row_headers.test.js, test/features/row_mouse_selection/selecting_one_row.test.js, test/features/row_mouse_selection/selecting_one_row_range.test.js, test/features/row_mouse_selection/selecting_row_headers.test.js, test/features/row_mouse_selection/selecting_two_rows.test.js, test/features/row_mouse_selection/splitting_one_row_range.test.js
The `getMeta()` function should not causes renders by simply calling it, but due to the shared-code between this method and the renderer, calling `getMeta()` with an `ridx` value beyond the row cache created empty `<tr>` elements. This PR address this issue and fixes tests.
=> Fix `getMeta()` bug

README.md, src/js/table.js, src/js/tbody.js, src/js/thead.js, src/js/view_model.js, test/features/row_mouse_selection/selecting_grouped_row_headers.test.js, test/features/row_mouse_selection/selecting_one_row.test.js, test/features/row_mouse_selection/selecting_one_row_range.test.js, test/features/row_mouse_selection/selecting_row_headers.test.js, test/features/row_mouse_selection/selecting_two_rows.test.js, test/features/row_mouse_selection/splitting_one_row_range.test.js
Adds `merge_headers` option, which can be `"both"` (default), `"row"`, `"horizontal"`, or `"none"`, similar to `virtual_mode` (but defined on the return object of a `setDataListener` callback, instead of as an optional argument). These new non-default modes disable merge behavior as described in "Column and row groups" in the documentation.
Fixes #193
=> Add `merge_headers` option

src/js/scroll_panel.js
Fixes a regression introduced in #184 which caused viewport to _always_ be considered stale, resulting in extraneous calls to the data listener which impacts scroll performance.
=> Fix viewport staleness check

src/js/scroll_panel.js
This PR fixes a geometry calculation bug in which caused the last column in a table to only be horizontally scrollable enough to allow this column to be in view, which caused columns wider than the viewport to be clipped.
=> Allow last column to be sub-cell scrolled
